### ISSUE TITLE
Troubleshooting why recitation-bot is not running in 2016

### ISSUE THREAD

**Issue by notconfusing** [wpoa/recitation-bot#53]
here's what I know: add_doi.py runs, and will take your input, but that input is not making it to task_supervisor.py

the faillog is no help, because this is supposed to be where the faillog is made:

http://tools.wmflabs.org/recitation-bot/faillog.html

from line 21 of task_supervisior.py

but there are no updates since 2014.

but another issue im seeing is that on line 35 of task_supervisor.py

tries to read ../jump_the_queue.log
 but is not. since you can see they are being added to this file to be read, but are not being cleared:

tools.recitation-bot@tools-bastion-03:~/recitation-bot$ cat jump_the_queue.log
10.7554/eLife.08347    []
10.3390/v4123531    []
10.7554/eLife.11750    []
10.1186/1756-3305-5-247    []
10.3897/phytokeys.57.6347    []
10.1086/173453    []
10.1371/journal.pone.0112634    []
10.1371/journal.pmed.1001644    []
  ssh-keygen -f "/home/notconfusing/.ssh/known_hosts" -R tools-login.wmflabs.org    []
10.1371/journal.pmed.1001644    []

so for some reason even though submit_bot_to_grid.sh is being executed:

tools.recitation-bot@tools-bastion-03:~$ cat submit_bot_to_grid.sh
jstart -l h_vmem=2g -quiet ~/pwb/bin/python ~/recitation-bot/recitation-bot/task_supervisor.py

task_supervisor is not executing. I would run it, not on Sun Grid Engine. To see if it's a grid enginge issue.

Make a great day,
Max Klein ‽ http://notconfusing.com/

**Comment by difranco** [comment]
Seems we may be suffering from this according to @notconfusing 
https://phabricator.wikimedia.org/T101228

**Comment by difranco** [comment]
Fixed 8 May.
